# Generated by Django 4.2.7 on 2023-11-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='cofirm',
            new_name='pass2',
        ),
    ]
