# Generated by Django 4.2.7 on 2023-11-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='usersignup',
        ),
    ]
